# Generated by Django 5.2.8 on 2025-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
